const cardImages: Record<string, any> = {
    "green-0": require("../assets/images/cards/green-0.png"),
    "green-1": require("../assets/images/cards/green-1.png"),
    "green-2": require("../assets/images/cards/green-2.png"),
    "green-3": require("../assets/images/cards/green-3.png"),
    "green-4": require("../assets/images/cards/green-4.png"),
    "green-5": require("../assets/images/cards/green-5.png"),
    "green-6": require("../assets/images/cards/green-6.png"),
    "green-7": require("../assets/images/cards/green-7.png"),
    "green-8": require("../assets/images/cards/green-8.png"),
    "green-9": require("../assets/images/cards/green-9.png"),
    "green-reverse": require("../assets/images/cards/green-reverse.png"),
    "green-skip": require("../assets/images/cards/green-skip.png"),
    "green-draw_2": require("../assets/images/cards/green-draw_2.png"),

    "yellow-0": require("../assets/images/cards/yellow-0.png"),
    "yellow-1": require("../assets/images/cards/yellow-1.png"),
    "yellow-2": require("../assets/images/cards/yellow-2.png"),
    "yellow-3": require("../assets/images/cards/yellow-3.png"),
    "yellow-4": require("../assets/images/cards/yellow-4.png"),
    "yellow-5": require("../assets/images/cards/yellow-5.png"),
    "yellow-6": require("../assets/images/cards/yellow-6.png"),
    "yellow-7": require("../assets/images/cards/yellow-7.png"),
    "yellow-8": require("../assets/images/cards/yellow-8.png"),
    "yellow-9": require("../assets/images/cards/yellow-9.png"),
    "yellow-reverse": require("../assets/images/cards/yellow-reverse.png"),
    "yellow-skip": require("../assets/images/cards/yellow-skip.png"),
    "yellow-draw_2": require("../assets/images/cards/yellow-draw_2.png"),

    "red-0": require("../assets/images/cards/red-0.png"),
    "red-1": require("../assets/images/cards/red-1.png"),
    "red-2": require("../assets/images/cards/red-2.png"),
    "red-3": require("../assets/images/cards/red-3.png"),
    "red-4": require("../assets/images/cards/red-4.png"),
    "red-5": require("../assets/images/cards/red-5.png"),
    "red-6": require("../assets/images/cards/red-6.png"),
    "red-7": require("../assets/images/cards/red-7.png"),
    "red-8": require("../assets/images/cards/red-8.png"),
    "red-9": require("../assets/images/cards/red-9.png"),
    "red-reverse": require("../assets/images/cards/red-reverse.png"),
    "red-skip": require("../assets/images/cards/red-skip.png"),
    "red-draw_2": require("../assets/images/cards/red-draw_2.png"),

    "blue-0": require("../assets/images/cards/blue-0.png"),
    "blue-1": require("../assets/images/cards/blue-1.png"),
    "blue-2": require("../assets/images/cards/blue-2.png"),
    "blue-3": require("../assets/images/cards/blue-3.png"),
    "blue-4": require("../assets/images/cards/blue-4.png"),
    "blue-5": require("../assets/images/cards/blue-5.png"),
    "blue-6": require("../assets/images/cards/blue-6.png"),
    "blue-7": require("../assets/images/cards/blue-7.png"),
    "blue-8": require("../assets/images/cards/blue-8.png"),
    "blue-9": require("../assets/images/cards/blue-9.png"),
    "blue-reverse": require("../assets/images/cards/blue-reverse.png"),
    "blue-skip": require("../assets/images/cards/blue-skip.png"),
    "blue-draw_2": require("../assets/images/cards/blue-draw_2.png"),
    "wild-wild": require("../assets/images/cards/wild-wild.png"),
    "wild-draw_4": require("../assets/images/cards/wild-draw_4.png"),
    "default": require("../assets/images/cards/default.png"), // Fallback
  };
  
  export default cardImages;